spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
#    url: jdbc:h2:mem:test
    url: ${ENDPOINT}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#  logging:
#    level:
#      com.zaxxer.hikari: TRACE
#      com.zaxxer.hikari.HikariConfig: DEBUG
#  h2:
#    console:
#      enabled: true
#      path: /h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #swagger 에러 해결
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: ec2-15-164-87-251.ap-northeast-2.compute.amazonaws.com # 로컬 환경에서는 localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
file:
  path: ${FILE_PATH}
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420
email:
  address:
    admin: admin@gmail.com
